#Server configuration
server:
  port: 8081
  servlet:
    context-path: /query

# Database connection
spring:
  datasource:    
    username: system
    password: oracle    
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    continue-on-error: false
    platform: oracle

# extra database configuration
  jpa:
  database: ORACLE
  show-sql: true
  generate-ddl: false
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect